baseURL: "https://abhatt-rh.github.io/patterns-docs/"
languageCode: "en-us"
title: "Hybrid Cloud Patterns"
theme: "ananke"
security:
  exec:
    osEnv:
    - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|HOME)$
    allow: ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
    
markup:
  asciidocExt:
    attributes: {} #allow-uri-read
    safeMode: unsafe
    backend: html5
    extensions: []
    failureLevel: fatal
    noHeaderOrFooter: true
    preserveTOC: true
    safeMode: unsafe
    sectionNumbers: true
    trace: true
    verbose: true
    workingFolderCurrent: false

