baseURL: "https://abhatt-rh.github.io/patterns-docs/"
languageCode: "en-us"
title: "Hybrid Cloud Patterns"
theme: "patternfly"
summaryLength: 20
paginate: 5
params:
  site_logo: hybrid_cloud_patterns.png
security:
  exec:
    osEnv:
    - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|HOME)$
    allow: ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
  funcs:
    getenv:
      - ^HUGO_

markup:
  asciidocExt:
    attributes: {allow-uri-read}
    safeMode: unsafe
  tableOfContents:
    startLevel: 1
    endLevel: 2
    ordered: false

taxonomies:
  industry: 'industries'
  product: 'products'
  blog_tag: 'blog_tags'

sectionPagesMenu: main

menu:
  main:
  - identifier: patterns
    name: Get Patterns
    title: Patterns
    url: /patterns/
    weight: 10
  - identifier: learn
    name: Learn
    title: Learn
    url: /learn/
    weight: 20
  - identifier: contribute
    name: Contribute
    title: Contribute
    url: /contribute/
    weight: 30
  - identifier: blog
    name: Blog
    title: Blog
    url: /blog/
    weight: 40